import Head from "next/head"
import Home from "./Home";
import Dashboard from "./Dashboard";


export default function index() {
  return (
    <>
      <Head>
        <title>Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
          <Home />
      </main>
    </>
  )
}
